### ISSUE TITLE
Test failing on fresh environment

### ISSUE THREAD

**Issue by donosonaumczuk** [kleros/kleros-v2#181]
A test is failing right after cloning the repository, installing dependencies and running tests.

```bash
  16 passing (7s)
  1 failing

  1) Draw Benchmark
       Draw Benchmark:
     Error: VM Exception while processing transaction: reverted with reason string 'Staking failed'
    at KlerosCore.onlyByGovernor (src/arbitration/KlerosCore.sol:179)
    at KlerosCore.setStake (src/arbitration/KlerosCore.sol:494)
    at async HardhatNode._mineBlockWithPendingTxs (/home/donosonaumczuk/Projects/Kleros/kleros-v2/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1773:23)
    at async HardhatNode.mineBlock (/home/donosonaumczuk/Projects/Kleros/kleros-v2/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:466:16)
    at async EthModule._sendTransactionAndReturnHash (/home/donosonaumczuk/Projects/Kleros/kleros-v2/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:1504:18)
    at async HardhatNetworkProvider.request (/home/donosonaumczuk/Projects/Kleros/kleros-v2/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:118:18)
    at async EthersProviderWrapper.send (/home/donosonaumczuk/Projects/Kleros/kleros-v2/node_modules/hardhat-deploy-ethers/src/internal/ethers-provider-wrapper.ts:13:20)

```

This was a known issue, the test has a comment in the failing line:
```solidity
      await core.connect(wallet).setStake(0, ONE_THOUSAND_PNK.mul(10), { gasLimit: 5000000 }); // Github Action fails here, no idea why.
```

I'm running Ubuntu 22.04, node v16, probably similar environment as GitHub Actions.

**Comment by jaybuidl** [comment]
Thanks for reporting. Initially we spent time trying to reproduce the failure and couldn’t, it seemed specific to the Github Actions environment. One day the failure started happening locally too. We need look into it. So the Github Actions test passes with env var `GITHUB_ACTIONS=true`. We need to fix this test.
